// Code generated by 'go generate game_of_stones/gen'. DO NOT EDIT.

//go:build connect6

package board

const (
	maxStones = 6
)

const WinScore = 2836

func scoreStones(stone, stones Stone) (Score, Score) {
	if stone == Black {
		switch stones {
		case 0x00:
			return 4, 0
		case 0x01:
			return 25, -5
		case 0x02:
			return 114, -30
		case 0x03:
			return 396, -144
		case 0x04:
			return 2836, -540
		case 0x10:
			return -1, 5
		case 0x20:
			return -6, 30
		case 0x30:
			return -36, 144
		case 0x40:
			return -180, 540
		}
	} else {
		switch stones {
		case 0x00:
			return 0, -4
		case 0x01:
			return -5, 1
		case 0x02:
			return -30, 6
		case 0x03:
			return -144, 36
		case 0x04:
			return -540, 180
		case 0x10:
			return 5, -25
		case 0x20:
			return 30, -114
		case 0x30:
			return 144, -396
		case 0x40:
			return 540, -2836
		}
	}
	return 0, 0
}
