// Code generated by 'go generate game_of_stones/gen'. DO NOT EDIT.

//go:build connect6 && debug

package board

func debugScoreStones(stones Stone) (Score, Score) {
	switch stones {
	case 0x00:
		return 1, -1
	case 0x01:
		return 5, -1
	case 0x02:
		return 30, -6
	case 0x03:
		return 144, -36
	case 0x04:
		return 540, -180
	case 0x05:
		return 3376, -720
	case 0x10:
		return 1, -5
	case 0x20:
		return 6, -30
	case 0x30:
		return 36, -144
	case 0x40:
		return 180, -540
	case 0x50:
		return 720, -3376

	}
	return 0, 0
}
