// Code generated by 'go generate game_of_stones/gen'. DO NOT EDIT.

//go:build connect6

package board

// 2, 16, 112, 672, 3360, 106048
func testScoreStones(stones Stone) (Score, Score) {
	switch stones {
	case 0x00:
		return 2, -2
	case 0x01:
		return 14, -2
	case 0x02:
		return 96, -16
	case 0x03:
		return 560, -112
	case 0x04:
		return 2688, -672
	case 0x05:
		return 102688, -3360
	case 0x10:
		return 2, -14
	case 0x20:
		return 16, -96
	case 0x30:
		return 112, -560
	case 0x40:
		return 672, -2688
	case 0x50:
		return 3360, -102688

	}
	return 0, 0
}
