// Code generated by 'go generate game_of_stones/...'. DO NOT EDIT.

//go:build connect6 && debug

package board

func debugStonesValues(stones Stone) (float32, float32) {
	switch stones {
	case 0x00:
		return 1, -1
	case 0x01:
		return 4, -1
	case 0x02:
		return 15, -5
	case 0x03:
		return 40, -20
	case 0x04:
		return 60, -60
	case 0x05:
		return 9880, -120
	case 0x10:
		return 1, -4
	case 0x20:
		return 5, -15
	case 0x30:
		return 20, -40
	case 0x40:
		return 60, -60
	case 0x50:
		return 120, -9880

	}
	return 0, 0
}

func debugStonesValue(stones Stone) float32 {
	switch stones {
	case 0x01:
		return 1
	case 0x02:
		return 5
	case 0x03:
		return 20
	case 0x04:
		return 60
	case 0x05:
		return 120
	case 0x06:
		return 10000
	case 0x10:
		return -1
	case 0x20:
		return -5
	case 0x30:
		return -20
	case 0x40:
		return -60
	case 0x50:
		return -120
	case 0x60:
		return -10000

	}
	return 0
}
