// Code generated by 'go generate game_of_stones/gen'. DO NOT EDIT.

//go:build gomoku

package board

const (
	maxStones = 5
)

const WinScore = 4096

func scoreStones(stone, stones Stone) (Score, Score) {
	if stone == Black {
		switch stones {
		case 0x00:
			return 6, 0
		case 0x01:
			return 49, -7
		case 0x02:
			return 328, -56
		case 0x03:
			return 3264, -384
		case 0x10:
			return -1, 7
		case 0x20:
			return -8, 56
		case 0x30:
			return -64, 384
		}
	} else {
		switch stones {
		case 0x00:
			return 0, -6
		case 0x01:
			return -7, 1
		case 0x02:
			return -56, 8
		case 0x03:
			return -384, 64
		case 0x10:
			return 7, -49
		case 0x20:
			return 56, -328
		case 0x30:
			return 384, -3264
		}
	}
	return 0, 0
}
