// Code generated by 'go generate game_of_stones/gen'. DO NOT EDIT.

//go:build gomoku

package board

import "game_of_stones/score"

const (
	maxStones = 5
)

func scoreStones(stone, stones Stone) (score.Score, score.Score) {
	if stone == Black {
		switch stones {
		case 0x00:
			return 12, 0
		case 0x01:
			return 66, -14
		case 0x02:
			return 208, -80
		case 0x03:
			return 100000, -288
		case 0x10:
			return -2, 14
		case 0x20:
			return -16, 80
		case 0x30:
			return -96, 288
		}
	} else {
		switch stones {
		case 0x00:
			return 0, -12
		case 0x01:
			return -14, 2
		case 0x02:
			return -80, 16
		case 0x03:
			return -288, 96
		case 0x10:
			return 14, -66
		case 0x20:
			return 80, -208
		case 0x30:
			return 288, -100000
		}
	}
	return 0, 0
}
