// Code generated by 'go generate game_of_stones/gen'. DO NOT EDIT.

//go:build gomoku

package board

const (
	maxStones = 5
)

func scoreStones(stone, stones Stone) (Score, Score) {
	if stone == Black {
		switch stones {
		case 0x00:
			return 12, 0
		case 0x01:
			return 82, -14
		case 0x02:
			return 464, -96
		case 0x03:
			return 100000, -560
		case 0x10:
			return -2, 14
		case 0x20:
			return -16, 96
		case 0x30:
			return -112, 560
		}
	} else {
		switch stones {
		case 0x00:
			return 0, -12
		case 0x01:
			return -14, 2
		case 0x02:
			return -96, 16
		case 0x03:
			return -560, 112
		case 0x10:
			return 14, -82
		case 0x20:
			return 96, -464
		case 0x30:
			return 560, -100000
		}
	}
	return 0, 0
}
