[project]
authors = ["Andrew Suprun <andrew.suprun@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
description = "Plays Gomoku and Connect6"
name = "Game of Stones"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
sim = "mojo run -I src apps/sim.mojo"

[dependencies]
max = ">=25.3.0.dev2025032005,<26"
python = ">=3.11,<3.13"
pygame = ">=2.6.1,<3"
